services:
  - type: web
    name: downloader-api
    runtime: python
    repo: https://github.com/tradevanataweb/download
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
